/* static_serie.c generated by valac 0.56.0, the Vala compiler
 * generated from static_serie.vala, do not modify */

#include "livechart.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <cairo-gobject.h>
#include <float.h>
#include <math.h>
#include <gee.h>
#include <gdk/gdk.h>

enum  {
	LIVE_CHART_STATIC_STATIC_SERIE_0_PROPERTY,
	LIVE_CHART_STATIC_STATIC_SERIE_NAME_PROPERTY,
	LIVE_CHART_STATIC_STATIC_SERIE_MAIN_COLOR_PROPERTY,
	LIVE_CHART_STATIC_STATIC_SERIE_LINE_PROPERTY,
	LIVE_CHART_STATIC_STATIC_SERIE_VISIBLE_PROPERTY,
	LIVE_CHART_STATIC_STATIC_SERIE_NUM_PROPERTIES
};
static GParamSpec* live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
enum  {
	LIVE_CHART_STATIC_STATIC_SERIE_VALUE_ADDED_SIGNAL,
	LIVE_CHART_STATIC_STATIC_SERIE_NUM_SIGNALS
};
static guint live_chart_static_static_serie_signals[LIVE_CHART_STATIC_STATIC_SERIE_NUM_SIGNALS] = {0};

struct _LiveChartStaticStaticSeriePrivate {
	gchar* _name;
	gboolean _visible;
	LiveChartStaticStaticSerieRenderer* renderer;
};

static gint LiveChartStaticStaticSerie_private_offset;
static gpointer live_chart_static_static_serie_parent_class = NULL;
static LiveChartColorableIface * live_chart_static_static_serie_live_chart_colorable_parent_iface = NULL;
static LiveChartDrawableIface * live_chart_static_static_serie_live_chart_drawable_parent_iface = NULL;

static void live_chart_static_static_serie_real_draw (LiveChartDrawable* base,
                                               cairo_t* ctx,
                                               LiveChartConfig* config);
static void live_chart_static_static_serie_real_get_bounding_box (LiveChartDrawable* base,
                                                           LiveChartBoundingBox* result);
static void live_chart_static_static_serie_finalize (GObject * obj);
static GType live_chart_static_static_serie_get_type_once (void);
static void _vala_live_chart_static_static_serie_get_property (GObject * object,
                                                        guint property_id,
                                                        GValue * value,
                                                        GParamSpec * pspec);
static void _vala_live_chart_static_static_serie_set_property (GObject * object,
                                                        guint property_id,
                                                        const GValue * value,
                                                        GParamSpec * pspec);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static inline gpointer
live_chart_static_static_serie_get_instance_private (LiveChartStaticStaticSerie* self)
{
	return G_STRUCT_MEMBER_P (self, LiveChartStaticStaticSerie_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 39 "../src/static/static_serie.vala"
	return self ? g_object_ref (self) : NULL;
#line 73 "static_serie.c"
}

LiveChartStaticStaticSerie*
live_chart_static_static_serie_construct (GType object_type,
                                          const gchar* name,
                                          LiveChartStaticStaticSerieRenderer* renderer)
{
	LiveChartStaticStaticSerie * self = NULL;
	LiveChartStaticStaticSerieRenderer* _tmp0_;
#line 37 "../src/static/static_serie.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 37 "../src/static/static_serie.vala"
	g_return_val_if_fail (renderer != NULL, NULL);
#line 37 "../src/static/static_serie.vala"
	self = (LiveChartStaticStaticSerie*) g_object_new (object_type, NULL);
#line 38 "../src/static/static_serie.vala"
	live_chart_static_static_serie_set_name (self, name);
#line 39 "../src/static/static_serie.vala"
	_tmp0_ = _g_object_ref0 (renderer);
#line 39 "../src/static/static_serie.vala"
	_g_object_unref0 (self->priv->renderer);
#line 39 "../src/static/static_serie.vala"
	self->priv->renderer = _tmp0_;
#line 37 "../src/static/static_serie.vala"
	return self;
#line 99 "static_serie.c"
}

LiveChartStaticStaticSerie*
live_chart_static_static_serie_new (const gchar* name,
                                    LiveChartStaticStaticSerieRenderer* renderer)
{
#line 37 "../src/static/static_serie.vala"
	return live_chart_static_static_serie_construct (LIVE_CHART_STATIC_TYPE_STATIC_SERIE, name, renderer);
#line 108 "static_serie.c"
}

static void
live_chart_static_static_serie_real_draw (LiveChartDrawable* base,
                                          cairo_t* ctx,
                                          LiveChartConfig* config)
{
	LiveChartStaticStaticSerie * self;
	gboolean _tmp0_;
	gboolean _tmp1_;
#line 42 "../src/static/static_serie.vala"
	self = (LiveChartStaticStaticSerie*) base;
#line 42 "../src/static/static_serie.vala"
	g_return_if_fail (ctx != NULL);
#line 42 "../src/static/static_serie.vala"
	g_return_if_fail (config != NULL);
#line 43 "../src/static/static_serie.vala"
	_tmp0_ = live_chart_drawable_get_visible ((LiveChartDrawable*) self);
#line 43 "../src/static/static_serie.vala"
	_tmp1_ = _tmp0_;
#line 43 "../src/static/static_serie.vala"
	if (_tmp1_) {
#line 131 "static_serie.c"
		LiveChartStaticStaticSerieRenderer* _tmp2_;
#line 44 "../src/static/static_serie.vala"
		_tmp2_ = self->priv->renderer;
#line 44 "../src/static/static_serie.vala"
		live_chart_static_static_serie_renderer_draw (_tmp2_, ctx, config);
#line 137 "static_serie.c"
	}
}

void
live_chart_static_static_serie_add (LiveChartStaticStaticSerie* self,
                                    const gchar* name,
                                    gdouble value)
{
	LiveChartStaticStaticSerieRenderer* _tmp0_;
	LiveChartStaticStaticValues* _tmp1_;
	LiveChartStaticStaticValues* _tmp2_;
	LiveChartStaticNamedValue _tmp3_ = {0};
#line 48 "../src/static/static_serie.vala"
	g_return_if_fail (self != NULL);
#line 48 "../src/static/static_serie.vala"
	g_return_if_fail (name != NULL);
#line 49 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 49 "../src/static/static_serie.vala"
	_tmp1_ = live_chart_static_static_serie_renderer_get_values (_tmp0_);
#line 49 "../src/static/static_serie.vala"
	_tmp2_ = _tmp1_;
#line 49 "../src/static/static_serie.vala"
	_g_free0 (_tmp3_.name);
#line 49 "../src/static/static_serie.vala"
	_tmp3_.name = name;
#line 49 "../src/static/static_serie.vala"
	_tmp3_.value = value;
#line 49 "../src/static/static_serie.vala"
	live_chart_static_static_values_add (_tmp2_, &_tmp3_);
#line 49 "../src/static/static_serie.vala"
	_g_object_unref0 (_tmp2_);
#line 50 "../src/static/static_serie.vala"
	g_signal_emit (self, live_chart_static_static_serie_signals[LIVE_CHART_STATIC_STATIC_SERIE_VALUE_ADDED_SIGNAL], 0, value);
#line 172 "static_serie.c"
}

LiveChartStaticStaticValues*
live_chart_static_static_serie_get_values (LiveChartStaticStaticSerie* self)
{
	LiveChartStaticStaticSerieRenderer* _tmp0_;
	LiveChartStaticStaticValues* _tmp1_;
	LiveChartStaticStaticValues* result;
#line 53 "../src/static/static_serie.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 54 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 54 "../src/static/static_serie.vala"
	_tmp1_ = live_chart_static_static_serie_renderer_get_values (_tmp0_);
#line 54 "../src/static/static_serie.vala"
	result = _tmp1_;
#line 54 "../src/static/static_serie.vala"
	return result;
#line 191 "static_serie.c"
}

void
live_chart_static_static_serie_clear (LiveChartStaticStaticSerie* self)
{
	LiveChartStaticStaticSerieRenderer* _tmp0_;
	LiveChartStaticStaticValues* _tmp1_;
	LiveChartStaticStaticValues* _tmp2_;
#line 57 "../src/static/static_serie.vala"
	g_return_if_fail (self != NULL);
#line 58 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 58 "../src/static/static_serie.vala"
	_tmp1_ = live_chart_static_static_serie_renderer_get_values (_tmp0_);
#line 58 "../src/static/static_serie.vala"
	_tmp2_ = _tmp1_;
#line 58 "../src/static/static_serie.vala"
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp2_);
#line 58 "../src/static/static_serie.vala"
	_g_object_unref0 (_tmp2_);
#line 212 "static_serie.c"
}

static void
live_chart_static_static_serie_real_get_bounding_box (LiveChartDrawable* base,
                                                      LiveChartBoundingBox* result)
{
	LiveChartStaticStaticSerie * self;
	LiveChartStaticStaticSerieRenderer* _tmp0_;
	LiveChartBoundingBox _tmp1_ = {0};
#line 61 "../src/static/static_serie.vala"
	self = (LiveChartStaticStaticSerie*) base;
#line 62 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 62 "../src/static/static_serie.vala"
	live_chart_drawable_get_bounding_box ((LiveChartDrawable*) _tmp0_, &_tmp1_);
#line 62 "../src/static/static_serie.vala"
	*result = _tmp1_;
#line 62 "../src/static/static_serie.vala"
	return;
#line 232 "static_serie.c"
}

const gchar*
live_chart_static_static_serie_get_name (LiveChartStaticStaticSerie* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 9 "../src/static/static_serie.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 9 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->_name;
#line 9 "../src/static/static_serie.vala"
	result = _tmp0_;
#line 9 "../src/static/static_serie.vala"
	return result;
#line 248 "static_serie.c"
}

void
live_chart_static_static_serie_set_name (LiveChartStaticStaticSerie* self,
                                         const gchar* value)
{
	gchar* old_value;
#line 9 "../src/static/static_serie.vala"
	g_return_if_fail (self != NULL);
#line 9 "../src/static/static_serie.vala"
	old_value = live_chart_static_static_serie_get_name (self);
#line 9 "../src/static/static_serie.vala"
	if (g_strcmp0 (value, old_value) != 0) {
#line 262 "static_serie.c"
		gchar* _tmp0_;
#line 9 "../src/static/static_serie.vala"
		_tmp0_ = g_strdup (value);
#line 9 "../src/static/static_serie.vala"
		_g_free0 (self->priv->_name);
#line 9 "../src/static/static_serie.vala"
		self->priv->_name = _tmp0_;
#line 9 "../src/static/static_serie.vala"
		g_object_notify_by_pspec ((GObject *) self, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_NAME_PROPERTY]);
#line 272 "static_serie.c"
	}
}

static void
live_chart_static_static_serie_real_get_main_color (LiveChartColorable* base,
                                                    GdkRGBA * result)
{
	LiveChartStaticStaticSerie* self;
	LiveChartStaticStaticSerieRenderer* _tmp0_;
	LiveChartPath* _tmp1_;
	LiveChartPath* _tmp2_;
	GdkRGBA _tmp3_ = {0};
	GdkRGBA _tmp4_;
#line 13 "../src/static/static_serie.vala"
	self = (LiveChartStaticStaticSerie*) base;
#line 14 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 14 "../src/static/static_serie.vala"
	_tmp1_ = live_chart_static_static_serie_renderer_get_line (_tmp0_);
#line 14 "../src/static/static_serie.vala"
	_tmp2_ = _tmp1_;
#line 14 "../src/static/static_serie.vala"
	live_chart_path_get_color (_tmp2_, &_tmp3_);
#line 14 "../src/static/static_serie.vala"
	_tmp4_ = _tmp3_;
#line 14 "../src/static/static_serie.vala"
	*result = _tmp4_;
#line 14 "../src/static/static_serie.vala"
	return;
#line 302 "static_serie.c"
}

static void
live_chart_static_static_serie_real_set_main_color (LiveChartColorable* base,
                                                    GdkRGBA * value)
{
	LiveChartStaticStaticSerie* self;
	LiveChartStaticStaticSerieRenderer* _tmp0_;
	LiveChartPath* _tmp1_;
	LiveChartPath* _tmp2_;
	GdkRGBA _tmp3_;
#line 17 "../src/static/static_serie.vala"
	self = (LiveChartStaticStaticSerie*) base;
#line 18 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 18 "../src/static/static_serie.vala"
	_tmp1_ = live_chart_static_static_serie_renderer_get_line (_tmp0_);
#line 18 "../src/static/static_serie.vala"
	_tmp2_ = _tmp1_;
#line 18 "../src/static/static_serie.vala"
	_tmp3_ = *value;
#line 18 "../src/static/static_serie.vala"
	live_chart_path_set_color (_tmp2_, &_tmp3_);
#line 17 "../src/static/static_serie.vala"
	g_object_notify_by_pspec ((GObject *) self, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_MAIN_COLOR_PROPERTY]);
#line 328 "static_serie.c"
}

LiveChartPath*
live_chart_static_static_serie_get_line (LiveChartStaticStaticSerie* self)
{
	LiveChartPath* result;
	LiveChartStaticStaticSerieRenderer* _tmp0_;
	LiveChartPath* _tmp1_;
	LiveChartPath* _tmp2_;
#line 22 "../src/static/static_serie.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 23 "../src/static/static_serie.vala"
	_tmp1_ = live_chart_static_static_serie_renderer_get_line (_tmp0_);
#line 23 "../src/static/static_serie.vala"
	_tmp2_ = _tmp1_;
#line 23 "../src/static/static_serie.vala"
	result = _tmp2_;
#line 23 "../src/static/static_serie.vala"
	return result;
#line 350 "static_serie.c"
}

void
live_chart_static_static_serie_set_line (LiveChartStaticStaticSerie* self,
                                         LiveChartPath* value)
{
	LiveChartStaticStaticSerieRenderer* _tmp0_;
#line 26 "../src/static/static_serie.vala"
	g_return_if_fail (self != NULL);
#line 27 "../src/static/static_serie.vala"
	_tmp0_ = self->priv->renderer;
#line 27 "../src/static/static_serie.vala"
	live_chart_static_static_serie_renderer_set_line (_tmp0_, value);
#line 26 "../src/static/static_serie.vala"
	g_object_notify_by_pspec ((GObject *) self, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_LINE_PROPERTY]);
#line 366 "static_serie.c"
}

static gboolean
live_chart_static_static_serie_real_get_visible (LiveChartDrawable* base)
{
	gboolean result;
	LiveChartStaticStaticSerie* self;
#line 31 "../src/static/static_serie.vala"
	self = (LiveChartStaticStaticSerie*) base;
#line 31 "../src/static/static_serie.vala"
	result = self->priv->_visible;
#line 31 "../src/static/static_serie.vala"
	return result;
#line 380 "static_serie.c"
}

static void
live_chart_static_static_serie_real_set_visible (LiveChartDrawable* base,
                                                 gboolean value)
{
	LiveChartStaticStaticSerie* self;
	gboolean old_value;
#line 31 "../src/static/static_serie.vala"
	self = (LiveChartStaticStaticSerie*) base;
#line 31 "../src/static/static_serie.vala"
	old_value = live_chart_static_static_serie_real_get_visible (base);
#line 31 "../src/static/static_serie.vala"
	if (old_value != value) {
#line 31 "../src/static/static_serie.vala"
		self->priv->_visible = value;
#line 31 "../src/static/static_serie.vala"
		g_object_notify_by_pspec ((GObject *) self, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_VISIBLE_PROPERTY]);
#line 399 "static_serie.c"
	}
}

static void
live_chart_static_static_serie_class_init (LiveChartStaticStaticSerieClass * klass,
                                           gpointer klass_data)
{
#line 6 "../src/static/static_serie.vala"
	live_chart_static_static_serie_parent_class = g_type_class_peek_parent (klass);
#line 6 "../src/static/static_serie.vala"
	g_type_class_adjust_private_offset (klass, &LiveChartStaticStaticSerie_private_offset);
#line 6 "../src/static/static_serie.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_live_chart_static_static_serie_get_property;
#line 6 "../src/static/static_serie.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_live_chart_static_static_serie_set_property;
#line 6 "../src/static/static_serie.vala"
	G_OBJECT_CLASS (klass)->finalize = live_chart_static_static_serie_finalize;
#line 6 "../src/static/static_serie.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIVE_CHART_STATIC_STATIC_SERIE_NAME_PROPERTY, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_NAME_PROPERTY] = g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 6 "../src/static/static_serie.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIVE_CHART_STATIC_STATIC_SERIE_MAIN_COLOR_PROPERTY, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_MAIN_COLOR_PROPERTY] = g_param_spec_boxed ("main-color", "main-color", "main-color", gdk_rgba_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 6 "../src/static/static_serie.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIVE_CHART_STATIC_STATIC_SERIE_LINE_PROPERTY, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_LINE_PROPERTY] = g_param_spec_object ("line", "line", "line", LIVE_CHART_TYPE_PATH, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 6 "../src/static/static_serie.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIVE_CHART_STATIC_STATIC_SERIE_VISIBLE_PROPERTY, live_chart_static_static_serie_properties[LIVE_CHART_STATIC_STATIC_SERIE_VISIBLE_PROPERTY] = g_param_spec_boolean ("visible", "visible", "visible", TRUE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 6 "../src/static/static_serie.vala"
	live_chart_static_static_serie_signals[LIVE_CHART_STATIC_STATIC_SERIE_VALUE_ADDED_SIGNAL] = g_signal_new ("value-added", LIVE_CHART_STATIC_TYPE_STATIC_SERIE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__DOUBLE, G_TYPE_NONE, 1, G_TYPE_DOUBLE);
#line 427 "static_serie.c"
}

static void
live_chart_static_static_serie_live_chart_colorable_interface_init (LiveChartColorableIface * iface,
                                                                    gpointer iface_data)
{
#line 6 "../src/static/static_serie.vala"
	live_chart_static_static_serie_live_chart_colorable_parent_iface = g_type_interface_peek_parent (iface);
#line 6 "../src/static/static_serie.vala"
	iface->get_main_color = live_chart_static_static_serie_real_get_main_color;
#line 6 "../src/static/static_serie.vala"
	iface->set_main_color = live_chart_static_static_serie_real_set_main_color;
#line 440 "static_serie.c"
}

static void
live_chart_static_static_serie_live_chart_drawable_interface_init (LiveChartDrawableIface * iface,
                                                                   gpointer iface_data)
{
#line 6 "../src/static/static_serie.vala"
	live_chart_static_static_serie_live_chart_drawable_parent_iface = g_type_interface_peek_parent (iface);
#line 6 "../src/static/static_serie.vala"
	iface->draw = (void (*) (LiveChartDrawable*, cairo_t*, LiveChartConfig*)) live_chart_static_static_serie_real_draw;
#line 6 "../src/static/static_serie.vala"
	iface->get_bounding_box = (void (*) (LiveChartDrawable*, LiveChartBoundingBox*)) live_chart_static_static_serie_real_get_bounding_box;
#line 6 "../src/static/static_serie.vala"
	iface->get_visible = live_chart_static_static_serie_real_get_visible;
#line 6 "../src/static/static_serie.vala"
	iface->set_visible = live_chart_static_static_serie_real_set_visible;
#line 457 "static_serie.c"
}

static void
live_chart_static_static_serie_instance_init (LiveChartStaticStaticSerie * self,
                                              gpointer klass)
{
#line 6 "../src/static/static_serie.vala"
	self->priv = live_chart_static_static_serie_get_instance_private (self);
#line 31 "../src/static/static_serie.vala"
	self->priv->_visible = TRUE;
#line 468 "static_serie.c"
}

static void
live_chart_static_static_serie_finalize (GObject * obj)
{
	LiveChartStaticStaticSerie * self;
#line 6 "../src/static/static_serie.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LIVE_CHART_STATIC_TYPE_STATIC_SERIE, LiveChartStaticStaticSerie);
#line 8 "../src/static/static_serie.vala"
	_g_free0 (self->priv->_name);
#line 35 "../src/static/static_serie.vala"
	_g_object_unref0 (self->priv->renderer);
#line 6 "../src/static/static_serie.vala"
	G_OBJECT_CLASS (live_chart_static_static_serie_parent_class)->finalize (obj);
#line 483 "static_serie.c"
}

static GType
live_chart_static_static_serie_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (LiveChartStaticStaticSerieClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) live_chart_static_static_serie_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LiveChartStaticStaticSerie), 0, (GInstanceInitFunc) live_chart_static_static_serie_instance_init, NULL };
	static const GInterfaceInfo live_chart_colorable_info = { (GInterfaceInitFunc) live_chart_static_static_serie_live_chart_colorable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	static const GInterfaceInfo live_chart_drawable_info = { (GInterfaceInitFunc) live_chart_static_static_serie_live_chart_drawable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType live_chart_static_static_serie_type_id;
	live_chart_static_static_serie_type_id = g_type_register_static (G_TYPE_OBJECT, "LiveChartStaticStaticSerie", &g_define_type_info, 0);
	g_type_add_interface_static (live_chart_static_static_serie_type_id, LIVE_CHART_TYPE_COLORABLE, &live_chart_colorable_info);
	g_type_add_interface_static (live_chart_static_static_serie_type_id, LIVE_CHART_TYPE_DRAWABLE, &live_chart_drawable_info);
	LiveChartStaticStaticSerie_private_offset = g_type_add_instance_private (live_chart_static_static_serie_type_id, sizeof (LiveChartStaticStaticSeriePrivate));
	return live_chart_static_static_serie_type_id;
}

GType
live_chart_static_static_serie_get_type (void)
{
	static volatile gsize live_chart_static_static_serie_type_id__once = 0;
	if (g_once_init_enter (&live_chart_static_static_serie_type_id__once)) {
		GType live_chart_static_static_serie_type_id;
		live_chart_static_static_serie_type_id = live_chart_static_static_serie_get_type_once ();
		g_once_init_leave (&live_chart_static_static_serie_type_id__once, live_chart_static_static_serie_type_id);
	}
	return live_chart_static_static_serie_type_id__once;
}

static void
_vala_live_chart_static_static_serie_get_property (GObject * object,
                                                   guint property_id,
                                                   GValue * value,
                                                   GParamSpec * pspec)
{
	LiveChartStaticStaticSerie * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, LIVE_CHART_STATIC_TYPE_STATIC_SERIE, LiveChartStaticStaticSerie);
#line 6 "../src/static/static_serie.vala"
	switch (property_id) {
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_NAME_PROPERTY:
#line 6 "../src/static/static_serie.vala"
		g_value_set_string (value, live_chart_static_static_serie_get_name (self));
#line 6 "../src/static/static_serie.vala"
		break;
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_MAIN_COLOR_PROPERTY:
#line 530 "static_serie.c"
		{
			GdkRGBA boxed;
#line 6 "../src/static/static_serie.vala"
			live_chart_colorable_get_main_color ((LiveChartColorable*) self, &boxed);
#line 6 "../src/static/static_serie.vala"
			g_value_set_boxed (value, &boxed);
#line 537 "static_serie.c"
		}
#line 6 "../src/static/static_serie.vala"
		break;
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_LINE_PROPERTY:
#line 6 "../src/static/static_serie.vala"
		g_value_set_object (value, live_chart_static_static_serie_get_line (self));
#line 6 "../src/static/static_serie.vala"
		break;
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_VISIBLE_PROPERTY:
#line 6 "../src/static/static_serie.vala"
		g_value_set_boolean (value, live_chart_drawable_get_visible ((LiveChartDrawable*) self));
#line 6 "../src/static/static_serie.vala"
		break;
#line 553 "static_serie.c"
		default:
#line 6 "../src/static/static_serie.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 6 "../src/static/static_serie.vala"
		break;
#line 559 "static_serie.c"
	}
}

static void
_vala_live_chart_static_static_serie_set_property (GObject * object,
                                                   guint property_id,
                                                   const GValue * value,
                                                   GParamSpec * pspec)
{
	LiveChartStaticStaticSerie * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, LIVE_CHART_STATIC_TYPE_STATIC_SERIE, LiveChartStaticStaticSerie);
#line 6 "../src/static/static_serie.vala"
	switch (property_id) {
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_NAME_PROPERTY:
#line 6 "../src/static/static_serie.vala"
		live_chart_static_static_serie_set_name (self, g_value_get_string (value));
#line 6 "../src/static/static_serie.vala"
		break;
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_MAIN_COLOR_PROPERTY:
#line 6 "../src/static/static_serie.vala"
		live_chart_colorable_set_main_color ((LiveChartColorable*) self, g_value_get_boxed (value));
#line 6 "../src/static/static_serie.vala"
		break;
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_LINE_PROPERTY:
#line 6 "../src/static/static_serie.vala"
		live_chart_static_static_serie_set_line (self, g_value_get_object (value));
#line 6 "../src/static/static_serie.vala"
		break;
#line 6 "../src/static/static_serie.vala"
		case LIVE_CHART_STATIC_STATIC_SERIE_VISIBLE_PROPERTY:
#line 6 "../src/static/static_serie.vala"
		live_chart_drawable_set_visible ((LiveChartDrawable*) self, g_value_get_boolean (value));
#line 6 "../src/static/static_serie.vala"
		break;
#line 597 "static_serie.c"
		default:
#line 6 "../src/static/static_serie.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 6 "../src/static/static_serie.vala"
		break;
#line 603 "static_serie.c"
	}
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

